# Generated by Django 3.2.7 on 2021-09-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210918_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updateds',
            new_name='updated',
        ),
    ]
